ALTER TABLE teams       ADD COLUMN IF NOT EXISTS photo_url VARCHAR(500);
ALTER TABLE players     ADD COLUMN IF NOT EXISTS photo_url VARCHAR(500);
ALTER TABLE tournament  ADD COLUMN IF NOT EXISTS logo_url  VARCHAR(500);
